### ISSUE TITLE
g++ is able to compile c++ file but not executable file

### ISSUE THREAD

**Issue by ankitsingh101** [allanlw/hphpc-docker#4]
My Terminal Commands

alias hphpc="/hphpc/hhvm/hphp/hphp/hphp"
cd src
touch fib.php
apt-get installed Vim
vim fib.php
`<?php
function fib($n){
  return 
    $n <2 ? $n : fib($n-2) + fib($n-1);
}
echo fib(38);
?>
`
hphpc -l 4 -k 1 -o out fib.php

```
hphpc -l 4 -k 1 -o /src/project/out fib.php
running hphp...
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
Analyzing Includes
Analyzing All
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
Corrected function return type Boolean -> Variant
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
Corrected function return type [0x1] -> Variant
parsing inputs...
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
parsing fib.php ...
Analyzing Includes
Analyzing All
parsing inputs took 0'00" (7786 us) wall time
pre-optimizing...
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
pre-optimizing took 0'00" (4160 us) wall time
analyze includes...
analyze includes took 0'00" (17 us) wall time
inferring types...
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
inferring types took 0'00" (4659 us) wall time
post-optimizing...
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
post-optimizing took 0'00" (5052 us) wall time
creating CPP files...
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
perf_event_open failed with: Operation not permitted
creating CPP files took 0'00" (64653 us) wall time
compiling and linking CPP files...
-- The C compiler identification is GNU\n-- The CXX compiler identification is GNU\n-- Check for working C compiler: /usr/bin/gcc\n-- Check for working C compiler: /usr/bin/gcc -- works\n-- Detecting C compiler ABI info\n-- Detecting C compiler ABI info - done\n-- Check for working CXX compiler: /usr/bin/c++\n-- Check for working CXX compiler: /usr/bin/c++ -- works\n-- Detecting CXX compiler ABI info\n-- Detecting CXX compiler ABI info - done\n-- CMAKE_PREFIX_PATH was missing, proceeding anyway\n-- Performing Test HAVE_GCC_44\n-- Performing Test HAVE_GCC_44 - Success\n-- Boost version: 1.46.1\n-- Found the following Boost libraries:\n--   system\n--   program_options\n--   filesystem\n-- Found LIBGLOG: /hphpc/lib/libglog.so \n-- Could NOT find LIBINOTIFY (missing:  LIBINOTIFY_LIBRARY LIBINOTIFY_INCLUDE_DIR) \n-- Found LIBUNWIND: /usr/lib/libunwind.so \n-- Could NOT find LIBICONV (missing:  LIBICONV_LIBRARY) \n-- Performing Test LIBICONV_CONST\n-- Performing Test LIBICONV_CONST - Failed\n-- MySQL Include dir: /usr/include  library dir: /usr/lib/x86_64-linux-gnu\n-- MySQL client libraries: mysqlclient_r\n-- Found LIBMEMCACHED: /usr/lib/libmemcached.so \n-- Found PCRE: /usr/lib/x86_64-linux-gnu/libpcre.so \n-- Found libevent: /hphpc/lib/libevent.so\n-- Looking for evhttp_bind_socket_with_fd\n-- Looking for evhttp_bind_socket_with_fd - found\n-- Looking for gdImagePng in /usr/lib/x86_64-linux-gnu/libgd.so\n-- Looking for gdImagePng in /usr/lib/x86_64-linux-gnu/libgd.so - found\n-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.3.4")\n-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so \n-- Looking for gdImageJpeg in /usr/lib/x86_64-linux-gnu/libgd.so\n-- Looking for gdImageJpeg in /usr/lib/x86_64-linux-gnu/libgd.so - found\n-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so \n-- Looking for gdImageGif in /usr/lib/x86_64-linux-gnu/libgd.so\n-- Looking for gdImageGif in /usr/lib/x86_64-linux-gnu/libgd.so - found\n-- Found GD: /usr/lib/x86_64-linux-gnu/libgd.so\n-- Found CURL: /hphpc/lib/libcurl.so \n-- Looking for curl_multi_select\n-- Looking for curl_multi_select - not found\n-- Looking for curl_multi_wait\n-- Looking for curl_multi_wait - found\n-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so \n-- Found EXPAT: /usr/lib/x86_64-linux-gnu/libexpat.so \n-- Found ICU header files in /usr/include\n-- Found ICU libraries: /usr/lib/libicuuc.so\n-- Found minimal tcmalloc: /usr/lib/libtcmalloc_minimal.so\n-- Found Intel TBB\n-- Found mcrypt: /usr/lib/libmcrypt.so\n-- checking for module 'openssl'\n--   found openssl, version 1.0.1\n-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1..1")\n-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so \n-- Looking for BZ2_bzCompressInit in /usr/lib/x86_64-linux-gnu/libbz2.so\n-- Looking for BZ2_bzCompressInit in /usr/lib/x86_64-linux-gnu/libbz2.so - found\n-- Found ONIGURUMA: /usr/lib/libonig.so \n-- Found ldap: /usr/lib/x86_64-linux-gnu/libldap.so;/usr/lib/x86_64-linux-gnu/liblber.so\n-- Found Readline: /usr/include \n-- Found LibElf: /usr/lib/x86_64-linux-gnu/libelf.so \n-- Found LibDwarf: /usr/lib/libdwarf.a \n-- Configuring done\n-- Generating done\n-- Build files have been written to: /src/project/out\nScanning dependencies of target program\n[  6%] Building CXX object CMakeFiles/program.dir/php/fib.cpp.o\n[ 12%] Building CXX object CMakeFiles/program.dir/sys/global_variables.cpp.o\n[ 18%] Building CXX object CMakeFiles/program.dir/sys/dynamic_table_class.cpp.o\n[ 25%] Building CXX object CMakeFiles/program.dir/sys/name_maps.cpp.o\n[ 31%] Building CXX object CMakeFiles/program.dir/sys/global_state.cpp.o\n[ 37%] Building CXX object CMakeFiles/program.dir/sys/main.cpp.o\n[ 43%] Building CXX object CMakeFiles/program.dir/sys/literal_strings_0.no.cpp.o\n[ 50%] Building CXX object CMakeFiles/program.dir/sys/class_map.cpp.o\n[ 56%] Building CXX object CMakeFiles/program.dir/sys/scalar_arrays_0.no.cpp.o\n[ 62%] Building CXX object CMakeFiles/program.dir/sys/scalar_arrays.no.cpp.o\n[ 68%] Building CXX object CMakeFiles/program.dir/sys/source_info.cpp.o\n[ 75%] Building CXX object CMakeFiles/program.dir/sys/scalar_integers.cpp.o\n[ 81%] Building CXX object CMakeFiles/program.dir/sys/cpputil.cpp.o\n[ 87%] Building CXX object CMakeFiles/program.dir/sys/dynamic_table_file.cpp.o\n[ 93%] Building CXX object CMakeFiles/program.dir/sys/dynamic_table_constant.cpp.o\n[100%] Building CXX object CMakeFiles/program.dir/sys/dynamic_table_func.cpp.o\nLinking CXX executable program\n[100%] Built target program\n
compiling and linking CPP files took 3'27" (207290766 us) wall time
running executable /src/project/out/program --file fib.php...
Output=39088169all files saved in /src/project/out ...
running hphp took 3'39" (219273118 us) wall time
```

i'm getting hphp failed

`cd out/php ls`
`fib.cpp  fib.fws.h  fib.h`

`hphpc fib.php`
39088169

```g++ -w -v -Wall -std=c++0x -l stdc++ -I/hphpc/hhvm/hphp/ -I/hphpc/hhvm/hphp/third_party/folly -I/hphpc/hhvm/hphp/third_party/double-conversion/src/ -I/hphpc/include -I/hphpc/hhvm/hphp/third_party/libsqlite3/ -I/hphpc/hhvm/hphp/system/gen/ -I/hphpc/hhvm/hphp/third_party/timelib/ -I/usr/include/libxml2/ -I/hphpc/hhvm/hphp/out/ -I/hphpc/hhvm/hphp/runtime/base/hphp.h fib.cpp -lboost_system```

```
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-werror --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)
COLLECT_GCC_OPTIONS='-w' '-v' '-Wall' '-std=c++0x' '-I' '/hphpc/hhvm/hphp/' '-I' '/hphpc/hhvm/hphp/third_party/folly' '-I' '/hphpc/hhvm/hphp/third_party/double-conversion/src/' '-I' '/hphpc/include' '-I' '/hphpc/hhvm/hphp/third_party/libsqlite3/' '-I' '/hphpc/hhvm/hphp/system/gen/' '-I' '/hphpc/hhvm/hphp/third_party/timelib/' '-I' '/usr/include/libxml2/' '-I' '/hphpc/hhvm/hphp/out/' '-I' '/hphpc/hhvm/hphp/runtime/base/hphp.h' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/4.6/cc1plus -quiet -v -I /hphpc/hhvm/hphp/ -I /hphpc/hhvm/hphp/third_party/folly -I /hphpc/hhvm/hphp/third_party/double-conversion/src/ -I /hphpc/include -I /hphpc/hhvm/hphp/third_party/libsqlite3/ -I /hphpc/hhvm/hphp/system/gen/ -I /hphpc/hhvm/hphp/third_party/timelib/ -I /usr/include/libxml2/ -I /hphpc/hhvm/hphp/out/ -I /hphpc/hhvm/hphp/runtime/base/hphp.h -imultilib . -imultiarch x86_64-linux-gnu -D_GNU_SOURCE fib.cpp -quiet -dumpbase fib.cpp -mtune=generic -march=x86-64 -auxbase fib -Wall -w -std=c++0x -version -fstack-protector -o /tmp/ccNxluJm.s
GNU C++ (Ubuntu/Linaro 4.6.3-1ubuntu5) version 4.6.3 (x86_64-linux-gnu)
	compiled by GNU C version 4.6.3, GMP version 5.0.2, MPFR version 3.1.0-p3, MPC version 0.9
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../x86_64-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /hphpc/hhvm/hphp/
 /hphpc/hhvm/hphp/third_party/folly
 /hphpc/hhvm/hphp/third_party/double-conversion/src/
 /hphpc/include
 /hphpc/hhvm/hphp/third_party/libsqlite3/
 /hphpc/hhvm/hphp/system/gen/
 /hphpc/hhvm/hphp/third_party/timelib/
 /usr/include/libxml2/
 /hphpc/hhvm/hphp/out/
 /usr/include/c++/4.6
 /usr/include/c++/4.6/x86_64-linux-gnu/.
 /usr/include/c++/4.6/backward
 /usr/lib/gcc/x86_64-linux-gnu/4.6/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/4.6/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
GNU C++ (Ubuntu/Linaro 4.6.3-1ubuntu5) version 4.6.3 (x86_64-linux-gnu)
	compiled by GNU C version 4.6.3, GMP version 5.0.2, MPFR version 3.1.0-p3, MPC version 0.9
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: 65b5171ac1bd7b3f07dbea6bdb24be3d
COLLECT_GCC_OPTIONS='-w' '-v' '-Wall' '-std=c++0x' '-I' '/hphpc/hhvm/hphp/' '-I' '/hphpc/hhvm/hphp/third_party/folly' '-I' '/hphpc/hhvm/hphp/third_party/double-conversion/src/' '-I' '/hphpc/include' '-I' '/hphpc/hhvm/hphp/third_party/libsqlite3/' '-I' '/hphpc/hhvm/hphp/system/gen/' '-I' '/hphpc/hhvm/hphp/third_party/timelib/' '-I' '/usr/include/libxml2/' '-I' '/hphpc/hhvm/hphp/out/' '-I' '/hphpc/hhvm/hphp/runtime/base/hphp.h' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 as --64 -o /tmp/ccLiUvN9.o /tmp/ccNxluJm.s
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/4.6/:/usr/lib/gcc/x86_64-linux-gnu/4.6/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/4.6/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/4.6/:/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-w' '-v' '-Wall' '-std=c++0x' '-I' '/hphpc/hhvm/hphp/' '-I' '/hphpc/hhvm/hphp/third_party/folly' '-I' '/hphpc/hhvm/hphp/third_party/double-conversion/src/' '-I' '/hphpc/include' '-I' '/hphpc/hhvm/hphp/third_party/libsqlite3/' '-I' '/hphpc/hhvm/hphp/system/gen/' '-I' '/hphpc/hhvm/hphp/third_party/timelib/' '-I' '/usr/include/libxml2/' '-I' '/hphpc/hhvm/hphp/out/' '-I' '/hphpc/hhvm/hphp/runtime/base/hphp.h' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/4.6/collect2 --sysroot=/ --build-id --no-add-needed --as-needed --eh-frame-hdr -m elf_x86_64 --hash-style=gnu -dynamic-linker /lib64/ld-linux-x86-64.so.2 -z relro /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../x86_64-linux-gnu/crt1.o /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/4.6/crtbegin.o -L/usr/lib/gcc/x86_64-linux-gnu/4.6 -L/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.6/../../.. -lstdc++ /tmp/ccLiUvN9.o -lboost_system -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/4.6/crtend.o /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../x86_64-linux-gnu/crtn.o
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
/tmp/ccLiUvN9.o: In function `HPHP::f_fib(HPHP::Variant const&)':
fib.cpp:(.text+0xed): undefined reference to `HPHP::FIFunctionMem::FIFunctionMem(char const*)'
fib.cpp:(.text+0xfd): undefined reference to `HPHP::ThreadInfo::s_threadInfo'
fib.cpp:(.text+0x1ae): undefined reference to `HPHP::Variant::~Variant()'
fib.cpp:(.text+0x1f0): undefined reference to `HPHP::Variant::~Variant()'
fib.cpp:(.text+0x207): undefined reference to `HPHP::Variant::operator+(HPHP::Variant const&) const'
fib.cpp:(.text+0x229): undefined reference to `HPHP::Variant::~Variant()'
fib.cpp:(.text+0x235): undefined reference to `HPHP::Variant::~Variant()'
fib.cpp:(.text+0x241): undefined reference to `HPHP::Variant::~Variant()'
fib.cpp:(.text+0x25a): undefined reference to `HPHP::Variant::Variant(HPHP::Variant const&)'
fib.cpp:(.text+0x269): undefined reference to `HPHP::Variant::~Variant()'
fib.cpp:(.text+0x278): undefined reference to `HPHP::FIFunctionMem::~FIFunctionMem()'
fib.cpp:(.text+0x298): undefined reference to `HPHP::Variant::~Variant()'
fib.cpp:(.text+0x2a9): undefined reference to `HPHP::Variant::~Variant()'
fib.cpp:(.text+0x2ba): undefined reference to `HPHP::Variant::~Variant()'
fib.cpp:(.text+0x2cb): undefined reference to `HPHP::Variant::~Variant()'
fib.cpp:(.text+0x2dc): undefined reference to `HPHP::Variant::~Variant()'
/tmp/ccLiUvN9.o:fib.cpp:(.text+0x2f0): more undefined references to `HPHP::Variant::~Variant()' follow
/tmp/ccLiUvN9.o: In function `HPHP::f_fib(HPHP::Variant const&)':
fib.cpp:(.text+0x304): undefined reference to `HPHP::FIFunctionMem::~FIFunctionMem()'
/tmp/ccLiUvN9.o: In function `HPHP::ifa_fib(void*, int, HPHP::Variant const&, HPHP::Variant const&, HPHP::Variant const&, HPHP::Variant const&, HPHP::Variant const&, HPHP::Variant const&)':
fib.cpp:(.text+0x359): undefined reference to `HPHP::throw_missing_arguments(char const*, int, int)'
fib.cpp:(.text+0x365): undefined reference to `HPHP::Variant::~Variant()'
fib.cpp:(.text+0x37f): undefined reference to `HPHP::null_variant'
/tmp/ccLiUvN9.o: In function `HPHP::i_fib(void*, HPHP::Array const&)':
fib.cpp:(.text+0x3c9): undefined reference to `HPHP::invoke_func_few_handler(void*, HPHP::Array const&, HPHP::Variant (*)(void*, int, HPHP::Variant const&, HPHP::Variant const&, HPHP::Variant const&, HPHP::Variant const&, HPHP::Variant const&, HPHP::Variant const&))'
/tmp/ccLiUvN9.o: In function `HPHP::pm_php$fib_php(bool, HPHP::LVariableTable*, HPHP::Globals*)':
fib.cpp:(.text+0x462): undefined reference to `HPHP::FIFunctionFS::FIFunctionFS(char const*, int)'
fib.cpp:(.text+0x46f): undefined reference to `HPHP::s_ssp1258e96c'
fib.cpp:(.text+0x48c): undefined reference to `HPHP::s_svibfdab04a'
fib.cpp:(.text+0x4d1): undefined reference to `HPHP::String::~String()'
fib.cpp:(.text+0x4dd): undefined reference to `HPHP::Variant::~Variant()'
fib.cpp:(.text+0x4fd): undefined reference to `HPHP::FIFunctionFS::~FIFunctionFS()'
fib.cpp:(.text+0x50e): undefined reference to `HPHP::String::~String()'
fib.cpp:(.text+0x51f): undefined reference to `HPHP::Variant::~Variant()'
fib.cpp:(.text+0x530): undefined reference to `HPHP::FIFunctionFS::~FIFunctionFS()'
/tmp/ccLiUvN9.o: In function `HPHP::Variant::operator=(HPHP::Variant const&)':
fib.cpp:(.text._ZN4HPHP7VariantaSERKS0_[HPHP::Variant::operator=(HPHP::Variant const&)]+0x1f): undefined reference to `HPHP::Variant::assign(HPHP::Variant const&)'
/tmp/ccLiUvN9.o: In function `HPHP::Variant::toString() const':
fib.cpp:(.text._ZNK4HPHP7Variant8toStringEv[HPHP::Variant::toString() const]+0x4f): undefined reference to `HPHP::Variant::toStringHelper() const'
/tmp/ccLiUvN9.o: In function `HPHP::operator-(HPHP::Variant const&, long)':
fib.cpp:(.text._ZN4HPHPmiERKNS_7VariantEl[HPHP::operator-(HPHP::Variant const&, long)]+0x24): undefined reference to `HPHP::Variant::Variant(HPHP::Variant const&)'
fib.cpp:(.text._ZN4HPHPmiERKNS_7VariantEl[HPHP::operator-(HPHP::Variant const&, long)]+0x37): undefined reference to `HPHP::Variant::operator-=(long)'
fib.cpp:(.text._ZN4HPHPmiERKNS_7VariantEl[HPHP::operator-(HPHP::Variant const&, long)]+0x49): undefined reference to `HPHP::Variant::Variant(HPHP::Variant const&)'
fib.cpp:(.text._ZN4HPHPmiERKNS_7VariantEl[HPHP::operator-(HPHP::Variant const&, long)]+0x55): undefined reference to `HPHP::Variant::~Variant()'
fib.cpp:(.text._ZN4HPHPmiERKNS_7VariantEl[HPHP::operator-(HPHP::Variant const&, long)]+0x6f): undefined reference to `HPHP::Variant::~Variant()'
/tmp/ccLiUvN9.o: In function `HPHP::echo(HPHP::String const&)':
fib.cpp:(.text._ZN4HPHP4echoERKNS_6StringE[HPHP::echo(HPHP::String const&)]+0x18): undefined reference to `HPHP::g_context'
fib.cpp:(.text._ZN4HPHP4echoERKNS_6StringE[HPHP::echo(HPHP::String const&)]+0x32): undefined reference to `HPHP::BaseExecutionContext::write(HPHP::String const&)'
/tmp/ccLiUvN9.o: In function `HPHP::less(HPHP::Variant const&, long)':
fib.cpp:(.text._ZN4HPHP4lessERKNS_7VariantEl[HPHP::less(HPHP::Variant const&, long)]+0x1f): undefined reference to `HPHP::Variant::less(long) const'
collect2: ld returned 1 exit status
`
```

**Comment by ankitsingh101** [comment]
@allanlw please reply back.

**Comment by allanlw** [comment]
Is there not a built binary in /src/project/out ? That is where the output should be.

I'm not sure what the question is. Your program is encountering errors because it needs to link against the HPHPC runtime library.

**Comment by ankitsingh101** [comment]
@allanlw you are right. I have the binary output in the out folder but I want to convert the cpp code into wasm code. would it be possible? I just want to compare the runtime 

Like I did in this video. I want how much wasm code will take time on node

**Comment by allanlw** [comment]
I think compiling HPHPC code to wasm is an interesting project, but not very easy.

HPHPC requires a runtime library that is compiled separately and linked in. This includes curl, glog, libevent and the libraries in https://github.com/facebook/hhvm/tree/f3ddbe63f17916052b15f119e980ec5ed64c45d3/hphp/third_party

You'll need to dig pretty far into HPHPC internals to get this to work. I doubt it's worth it for your case, but it's up to you. Unfortunately, I doubt I have much time to help.
